# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Yaalr
version:      0.02.9
version_from: lib/Apache/Yaalr.pm
installdirs:  site
requires:
    Template:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
